# Generated by Django 2.1.1 on 2018-10-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TAPlots',
            new_name='TA',
        ),
    ]
